### ISSUE TITLE
Support dark mode and light mode syncing with OS theme for Wallpapers

### ISSUE THREAD

**Issue by xmha97** [rocksdanister/lively#995]
https://user-images.githubusercontent.com/23485114/148655713-3858cbb9-1eb4-4665-a21d-75dd0dcfff50.mp4

**Comment by xmha97** [comment]
#160

**Comment by xmha97** [comment]
The dark mode is supported on CefSharp
You can test using https://github.com/cefsharp/CefSharp.MinimalExample

https://user-images.githubusercontent.com/23485114/148663213-f7898f23-5088-4da0-ab6c-41e458f8a580.mp4

**Comment by xmha97** [comment]
@rocksdanister Is it possible to do this?

**Comment by rocksdanister** [comment]
Looks like its supported already: https://github.com/cefsharp/CefSharp/issues/2741

**Comment by xmha97** [comment]
Ok, I'm closing this since it's out of scope for this app.
But why did everything work so well in the CefSharp example?
https://github.com/rocksdanister/lively/issues/995#issuecomment-1008178567

**Comment by rocksdanister** [comment]
Keep it open, will check later.

**Comment by rocksdanister** [comment]
Does adding this event shown here work?
https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript

```js
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
    const newColorScheme = event.matches ? "dark" : "light";
});
```

**Comment by xmha97** [comment]
[A Complete Guide to Dark Mode on the Web](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/)
```css
body {
  color: #222;
  background: #fff;
  font: 100% system-ui;
}
a {
  color: #0033cc;
}

@media (prefers-color-scheme: dark) {
  body {
    color: #eee;
    background: #121212;
  }

  body a {
    color: #809fff;
  }
}
```
