### ISSUE TITLE
Custom webpage cursor

### ISSUE THREAD

**Issue by xmha97** [rocksdanister/lively#996]
```css
html {
  cursor: url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%3E%3Cpath%20d%3D%22M4%200l16%2012.279-6.951%201.17%204.325%208.817-3.596%201.734-4.35-8.879-5.428%204.702z%22%20style%3D%22fill%3A%230072ff%3Bfill-opacity%3A1%22%20%2F%3E%3C%2Fsvg%3E") 6 6, auto;
}
```

# CefSharp ✔️
![image](https://user-images.githubusercontent.com/23485114/148665746-e9a288ab-50da-4232-81e9-b860cc3b131b.png)

# Preview ✔️
![image](https://user-images.githubusercontent.com/23485114/148665841-b624ad2a-d5aa-4211-8520-bb9e78fdc77f.png)

# Wallpaper ❌
![image](https://user-images.githubusercontent.com/23485114/148665860-fc80d9d3-9d37-4d9b-bb12-0bc8d0137887.png)
